FROM python:3.6.4

# Set working directory
WORKDIR /dbu2cal

# Install Python requirements
COPY requirements.txt ./
RUN pip3 install --upgrade pip
RUN pip3 install --no-cache-dir -r requirements.txt

# Copy only necessary files
COPY app.py ./
COPY dbu2cal.py ./
COPY templates ./templates

# Set environment variables
ENV FLASK_APP=app.py

# Expose port
EXPOSE 5000

# Run the command on container startup
CMD python app.py
