version: '3'
services:
  app:
    build:
      context: ./
      dockerfile: ./Dockerfile.web
    ports:
      - 5000:5000
    volumes:
      - ./calendars:/dbu2cal/calendars
    restart: unless-stopped
  cron:
    build:
      context: ./
      dockerfile: ./Dockerfile.cron
    volumes:
      - ./calendars:/dbu2cal/calendars
    restart: unless-stopped
